In [1]:
print("Day - 1")

Day - 1

In [ ]:
# Lambda Practice

In [2]:
square = lambda x: x*x

In [3]:
square(5)

25

In [4]:
sum = lambda x,y,z: x+y+z

In [5]:
sum(3,4,5)

12

In [24]:
import pandas as pd
import numpy as np

In [8]:
df = pd.DataFrame({'Marks':[45,82,75]})

# Normalize marks (divide by 100)
df['Normalized'] = df['Marks'].apply(lambda x: x/100)
df

   Marks  Normalized
0     45        0.45
1     82        0.82
2     75        0.75

In [ ]:
# List Comprehension

In [23]:
num = [1,2,3,4,5,6,7,8,9,10]
perfect = [x**2 for x in num]
perfect

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [13]:
even = [x for x in num if x%2==0]
even

[2, 4, 6, 8, 10]

In [14]:
odd = [x for x in num if x%2!=0]
odd

[1, 3, 5, 7, 9]

In [17]:
df["Pass"] = ["Yes" if x>50 else "No" for x in df["Marks"]]
df

   Marks  Normalized Pass
0     45        0.45   No
1     82        0.82  Yes
2     75        0.75  Yes

In [ ]:
# Dictionary Comprehension

In [18]:
perfect_dict = {x:x**2 for x in num}
perfect_dict

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}

In [19]:
even_perfect_dict = {x:x**2 for x in num if x%2!=1}
even_perfect_dict

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100}

In [ ]:
# Practice Questions

In [29]:
np.random.seed(42)  # for consistent results

data = {
    "Student": ["Ali", "Sara", "Zara", "Ahmed", "Ayesha", "Bilal", "Hina", "Usman"],
    "Math": np.random.randint(30, 100, 8),
    "Physics": np.random.randint(30, 100, 8),
    "Chemistry": np.random.randint(30, 100, 8),
    "Attendance": np.random.randint(60, 100, 8)
}

df = pd.DataFrame(data)
df

  Student  Math  Physics  Chemistry  Attendance
0     Ali    81       31         87          62
1    Sara    44       59         51          96
2    Zara    90       67         78          66
3   Ahmed    50       31         88          80
4  Ayesha    53       93         71          68
5   Bilal    32       89         89          98
6    Hina    51       50         44          77
7   Usman    82       62         91          63

In [31]:
df["Math_Normalized"] = df["Math"].apply(lambda x: x/100)
df

  Student  Math  Physics  Chemistry  Attendance  Math_Normalized
0     Ali    81       31         87          62             0.81
1    Sara    44       59         51          96             0.44
2    Zara    90       67         78          66             0.90
3   Ahmed    50       31         88          80             0.50
4  Ayesha    53       93         71          68             0.53
5   Bilal    32       89         89          98             0.32
6    Hina    51       50         44          77             0.51
7   Usman    82       62         91          63             0.82

In [33]:
df["Result"] = ["Pass" if x > 50 else "Fail" for x in df["Math"]]
df

  Student  Math  Physics  Chemistry  Attendance  Math_Normalized Result
0     Ali    81       31         87          62             0.81   Pass
1    Sara    44       59         51          96             0.44   Fail
2    Zara    90       67         78          66             0.90   Pass
3   Ahmed    50       31         88          80             0.50   Fail
4  Ayesha    53       93         71          68             0.53   Pass
5   Bilal    32       89         89          98             0.32   Fail
6    Hina    51       50         44          77             0.51   Pass
7   Usman    82       62         91          63             0.82   Pass

In [35]:
df["Performance_Level"] = ["Excellent" if x>=80 else "Averege" if x>=50 else "Poor" for x in df["Math"]]
df

,Student,Math,Physics,Chemistry,Attendance,Math_Normalized,Result,Performance_Level
0,Ali,81,31,87,62,0.81,Pass,Excellent
1,Sara,44,59,51,96,0.44,Fail,Poor
2,Zara,90,67,78,66,0.90,Pass,Excellent
3,Ahmed,50,31,88,80,0.50,Fail,Averege
4,Ayesha,53,93,71,68,0.53,Pass,Averege
5,Bilal,32,89,89,98,0.32,Fail,Poor
6,Hina,51,50,44,77,0.51,Pass,Averege
7,Usman,82,62,91,63,0.82,Pass,Excellent

In [42]:
physics_normalized = [y/100 for x,y in zip(df["Attendance"], df["Physics"]) if x>=75]
physics_normalized

[0.59, 0.31, 0.89, 0.5]

In [41]:
pn = []
for x,y in zip(df["Attendance"], df["Physics"]):
    if x>=75:
        pn.append(y)

pn

[59, 31, 89, 50]

In [44]:
std = {x:a+b+c for x,a,b,c in zip(df["Student"], df["Math"], df["Physics"], df["Chemistry"])}
std

{'Ali': 199,
 'Sara': 154,
 'Zara': 235,
 'Ahmed': 169,
 'Ayesha': 217,
 'Bilal': 210,
 'Hina': 145,
 'Usman': 235}

In [52]:
df["Math"] = [x+5 if y>=70 else x for x,y in zip(df["Math"], df["Chemistry"])]
df

,Student,Math,Physics,Chemistry,Attendance,Math_Normalized,Result,Performance_Level
0,Ali,86,31,87,62,0.81,Pass,Excellent
1,Sara,44,59,51,96,0.44,Fail,Poor
2,Zara,95,67,78,66,0.90,Pass,Excellent
3,Ahmed,55,31,88,80,0.50,Fail,Averege
4,Ayesha,58,93,71,68,0.53,Pass,Averege
5,Bilal,37,89,89,98,0.32,Fail,Poor
6,Hina,51,50,44,77,0.51,Pass,Averege
7,Usman,87,62,91,63,0.82,Pass,Excellent